# Generated by Django 4.0.3 on 2022-03-13 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_workers_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custom_user',
            name='category_worker',
        ),
        migrations.AlterField(
            model_name='workers',
            name='category_worker',
            field=models.CharField(blank=True, choices=[('An', 'Admin'), ('Pt', 'Post admin'), ('Bg', 'Blog admin')], max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='Category_worker',
        ),
    ]
