# Generated by Django 4.0.3 on 2022-03-13 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_custom_user_category_worker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='category_worker',
            field=models.CharField(blank=True, choices=[('An', 'Admin'), ('Pt', 'Post admin'), ('Bg', 'Blog admin')], max_length=10, null=True),
        ),
    ]
